/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gradetracker.gui;

import gradetracker.logic.Assessment;
import gradetracker.logic.Subject;
import java.util.Date;
import javax.swing.ComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author kenmcclure
 */
public class DlgAssessment extends javax.swing.JDialog {

    Assessment assessment;

    /**
     * Creates new form DlgAssessment
     */
    public DlgAssessment(java.awt.Frame parent, boolean modal, Assessment selectedAssessment) {
        super(parent, modal);
        this.assessment = selectedAssessment;

        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);

        if (selectedAssessment != null) {
            //then we are editing
            /*
    Date date;
    String reflection;
    String name;
    int score;
    int outOf;
    float weight;
             */
            this.txtTopic.setText(assessment.getName());
            this.txtReflection.setText(assessment.getReflection());
            this.txtOutOf.setText("" + assessment.getOutOf());
            this.txtScore.setText("" + assessment.getScore());
            this.txtDate.setText(assessment.getDate().toString());
            //this.cmbType.setSelectedValue(assessment.getType());
            setAssessmentTypeByValue(assessment.getType());

        } else {
            //Inserting new Assessment
        }
    }

    private void setAssessmentTypeByValue(String type) {
        ComboBoxModel model = this.cmbType.getModel();
        for (int i = 0; i < model.getSize(); i++) {
            if (model.getElementAt(i).equals(type)) {
                model.setSelectedItem(i);
                break;
            } else {
                System.out.println("Didn't find " + type + " in the combo box");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTopic = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblScore = new javax.swing.JLabel();
        lblOutOf = new javax.swing.JLabel();
        txtTopic = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        txtScore = new javax.swing.JTextField();
        txtOutOf = new javax.swing.JTextField();
        cmbType = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblAssessmentsTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtReflection = new javax.swing.JTextArea();
        lblReflexion = new javax.swing.JLabel();
        lblWeight = new javax.swing.JLabel();
        txtWeight = new javax.swing.JTextField();
        lblWeightHint = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTopic.setText("Topic:");
        getContentPane().add(lblTopic, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        lblType.setText("Type:");
        getContentPane().add(lblType, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        lblDate.setText("Date:");
        getContentPane().add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        lblScore.setText("Score:");
        getContentPane().add(lblScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        lblOutOf.setText("Out of:");
        getContentPane().add(lblOutOf, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));
        getContentPane().add(txtTopic, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 270, -1));
        getContentPane().add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 270, -1));
        getContentPane().add(txtScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 140, -1));
        getContentPane().add(txtOutOf, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 140, -1));

        cmbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Test", "Exam", "Assignment", "Homework", "IA", "Other" }));
        getContentPane().add(cmbType, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, -1, -1));

        lblAssessmentsTitle.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lblAssessmentsTitle.setText("Assessments");
        getContentPane().add(lblAssessmentsTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 317, 40));

        txtReflection.setColumns(20);
        txtReflection.setRows(5);
        jScrollPane1.setViewportView(txtReflection);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 300, 290));

        lblReflexion.setText("Reflection:");
        getContentPane().add(lblReflexion, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        lblWeight.setText("Weight:");
        getContentPane().add(lblWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));
        getContentPane().add(txtWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 80, -1));

        lblWeightHint.setText("(0 to 100)");
        getContentPane().add(lblWeightHint, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        /*  if (assessment==null){
            //inserting new assessment
            
            Assessment newAssessment=new Assessment();
            
                Date date;
    String reflection;
    String name;
    int score;
    int outOf;
    int weight;
    String type;
         */
 /*
            newAssessment.setDate(Date.parse(txtDate.getText()));
            newAssessment.setReflection(txtReflection.getText());
            newAssessment.setName(txtTopic.getText());
            newAssessment.setOutOf(txtOutOf.getText());
            newAssessment.setWeight(txtScore.getText());
            newAssessment.setWeight(txtWeight.getText());
            newAssessment.setType(cmbType.getSelectedItem().toString());
            
            String teacher=txtTeacher.getText();
            boolean hl=chkHL.isSelected();
            int level=cmbLevel.getSelectedIndex()+1;
            Subject toInsert=new Subject(name,teacher,hl,level);       
        } else {
           //Editing existing subject
            subject.name=txtSubject.getText();
            subject.teacher=txtTeacher.getText();
            subject.HLorNot=chkHL.isSelected();
            subject.currentLevel=cmbLevel.getSelectedIndex()+1;    
        }
        Global.saveToFile();
        JOptionPane.showMessageDialog(null, "Your changes have been saved", "Save Subject", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
         */
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgAssessment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgAssessment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgAssessment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgAssessment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgAssessment dialog = new DlgAssessment(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbType;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAssessmentsTitle;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblOutOf;
    private javax.swing.JLabel lblReflexion;
    private javax.swing.JLabel lblScore;
    private javax.swing.JLabel lblTopic;
    private javax.swing.JLabel lblType;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JLabel lblWeightHint;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtOutOf;
    private javax.swing.JTextArea txtReflection;
    private javax.swing.JTextField txtScore;
    private javax.swing.JTextField txtTopic;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
