/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gradetracker.gui;

import gradetracker.logic.Assessment;
import gradetracker.logic.Subject;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author kenmcclure
 */
public class DlgAssessment extends javax.swing.JDialog {

    //State (variables) of the class
    Assessment assessment;  //holds a reference to the assessment being edited
    //of null if a new one is being assed
    Subject subject;        //holds a reference to the subject this assessment
    //belings to

    //The following code is the behaviour of the class
    public DlgAssessment(java.awt.Frame parent, boolean modal, Subject subject, Assessment selectedAssessment) {
        //centre the form on screen and set up close operation etc
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);

        //remember the assessment and subject that are passed in (put them in the state variables above)
        this.assessment = selectedAssessment;
        this.subject = subject;
        //fill in the data from the assessment onto the form to edit
        refreshDataOnForm();
    }

    private void refreshDataOnForm() {
        if (assessment != null) {
            //then we are editing
            this.lblMode.setText("Editing");
            this.txtTopic.setText(assessment.getName());
            this.txtReflection.setText(assessment.getReflection());
            this.txtOutOf.setText("" + assessment.getOutOf());
            this.txtScore.setText("" + assessment.getScore());
            this.txtWeight.setText("" + assessment.getWeight());
            DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            if (assessment.getDate() != null) {
                this.txtDate.setText(dateFormat.format(assessment.getDate()));
            }
            //this.cmbType.setSelectedValue(assessment.getType());
            setAssessmentTypeByValue(assessment.getType());
            cmbLevel.setSelectedIndex(assessment.getLevel() - 1);
        } else {
            //Inserting new Assessment
            lblMode.setText("Adding");
        }
    }

    //This method is used to simply set the combo box (assessment type)
    //so that it is selecting the correct assessment type when editing 
    //an existing assessment        
    private void setAssessmentTypeByValue(String type) {
        ComboBoxModel model = this.cmbType.getModel();
        for (int i = 0; i < model.getSize(); i++) {
            if (model.getElementAt(i).equals(type)) {
                cmbType.setSelectedIndex(i);
                break;
            } else {
                System.out.println("Didn't find " + type + " in the combo box");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTopic = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblScore = new javax.swing.JLabel();
        lblOutOf = new javax.swing.JLabel();
        lblMode = new javax.swing.JLabel();
        txtTopic = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        txtScore = new javax.swing.JTextField();
        txtOutOf = new javax.swing.JTextField();
        cmbType = new javax.swing.JComboBox<>();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        lblAssessmentsTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtReflection = new javax.swing.JTextArea();
        lblReflexion = new javax.swing.JLabel();
        lblWeight = new javax.swing.JLabel();
        txtWeight = new javax.swing.JTextField();
        lblWeightHint = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblLevel = new javax.swing.JLabel();
        cmbLevel = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTopic.setText("Topic:");
        getContentPane().add(lblTopic, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        lblType.setText("Type:");
        getContentPane().add(lblType, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        lblDate.setText("Date:");
        getContentPane().add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        lblScore.setText("Score:");
        getContentPane().add(lblScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        lblOutOf.setText("Out of:");
        getContentPane().add(lblOutOf, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        lblMode.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(lblMode, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 120, 20));
        getContentPane().add(txtTopic, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 270, -1));
        getContentPane().add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 140, -1));
        getContentPane().add(txtScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 140, -1));
        getContentPane().add(txtOutOf, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 140, -1));

        cmbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Test", "Exam", "Assignment", "Homework", "IA", "Other" }));
        getContentPane().add(cmbType, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, -1, -1));

        lblAssessmentsTitle.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lblAssessmentsTitle.setText("Assessments");
        getContentPane().add(lblAssessmentsTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 317, 40));

        txtReflection.setColumns(20);
        txtReflection.setRows(5);
        jScrollPane1.setViewportView(txtReflection);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 300, 290));

        lblReflexion.setText("Reflection:");
        getContentPane().add(lblReflexion, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        lblWeight.setText("Weight:");
        getContentPane().add(lblWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));
        getContentPane().add(txtWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 80, -1));

        lblWeightHint.setText("(0 to 100)");
        getContentPane().add(lblWeightHint, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));

        jLabel1.setText("eg. 17/12/2019");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        lblLevel.setText("Level:");
        getContentPane().add(lblLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        cmbLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7" }));
        getContentPane().add(cmbLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        //Close the form without saving if the user presses cancel
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // If the user presses save, then either:
        // a new assessment is added (if inserting)
        // or the changes are saved (if editing)

        boolean inserting = false;
        if (assessment == null) {
            //inserting new assessment
           assessment = new Assessment();
            inserting = true;
        }
        //is the date typed in the correct format?
        try {
            Date date1 = new SimpleDateFormat("dd/MM/yyyy").parse(txtDate.getText());
            assessment.setDate(date1);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Invalid date format, please correct it before saving", "Save Assessment", JOptionPane.ERROR_MESSAGE);
            return; // drop out of save
        }
        //add the screen fields into the data model
        assessment.setReflection(txtReflection.getText());
        assessment.setName(txtTopic.getText());
        assessment.setOutOf(Integer.parseInt(txtOutOf.getText()));
        assessment.setScore(Integer.parseInt(txtScore.getText()));
        assessment.setWeight(Integer.parseInt(txtWeight.getText()));
        assessment.setType(cmbType.getSelectedItem().toString());
        assessment.setLevel(cmbLevel.getSelectedIndex() + 1);
        //if inserting rather than editing, add that assessment to the subject
        if (inserting) {
            subject.addAssessment(assessment);
        }

        Global.saveToFile();
        JOptionPane.showMessageDialog(null, "Your changes have been saved", "Save Assessment", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();

    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgAssessment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgAssessment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgAssessment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgAssessment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgAssessment dialog = new DlgAssessment(new javax.swing.JFrame(), true, null, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbLevel;
    private javax.swing.JComboBox<String> cmbType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAssessmentsTitle;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblMode;
    private javax.swing.JLabel lblOutOf;
    private javax.swing.JLabel lblReflexion;
    private javax.swing.JLabel lblScore;
    private javax.swing.JLabel lblTopic;
    private javax.swing.JLabel lblType;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JLabel lblWeightHint;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtOutOf;
    private javax.swing.JTextArea txtReflection;
    private javax.swing.JTextField txtScore;
    private javax.swing.JTextField txtTopic;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
