/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gradetracker.gui;

import javax.swing.JFrame;

/**
 *
 * @author kenmcclure
 */
public class SubjectForm extends javax.swing.JFrame {

    /**
     * Creates new form Assessment
     */
    public SubjectForm() {
        initComponents();
        setLocationRelativeTo(null);  //this will move my form to the middle
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

 
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGraph = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservations = new javax.swing.JTextArea();
        lblObservations = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        lblSubject = new javax.swing.JLabel();
        lblTeacher = new javax.swing.JLabel();
        txtSubject = new javax.swing.JTextField();
        txtTeacher = new javax.swing.JTextField();
        lblAssessmentsTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblGraph.setText("(The graph will go here)");
        lblGraph.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblGraph, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 520, 180));

        txtObservations.setColumns(20);
        txtObservations.setRows(5);
        jScrollPane1.setViewportView(txtObservations);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 530, 100));

        lblObservations.setText("Observations:");
        getContentPane().add(lblObservations, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, -1));

        lblSubject.setText("Subject:");
        getContentPane().add(lblSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        lblTeacher.setText("Teacher:");
        getContentPane().add(lblTeacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        txtSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubjectActionPerformed(evt);
            }
        });
        getContentPane().add(txtSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 330, -1));
        getContentPane().add(txtTeacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 330, -1));

        lblAssessmentsTitle.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lblAssessmentsTitle.setText("Subject and Assessments");
        getContentPane().add(lblAssessmentsTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 530, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubjectActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        AssessmentForm af= new AssessmentForm();
        af.setVisible(true);
    }//GEN-LAST:event_btnEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubjectForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubjectForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubjectForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubjectForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubjectForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAssessmentsTitle;
    private javax.swing.JLabel lblGraph;
    private javax.swing.JLabel lblObservations;
    private javax.swing.JLabel lblSubject;
    private javax.swing.JLabel lblTeacher;
    private javax.swing.JTextArea txtObservations;
    private javax.swing.JTextField txtSubject;
    private javax.swing.JTextField txtTeacher;
    // End of variables declaration//GEN-END:variables
}
